version: '3.8'
services:
  backend:
    build:
      context: ./backend
    working_dir: /rails
    entrypoint:
      - bash
      - /rails/entrypoint.sh
    command:
      - bundle
      - exec
      - rails
      - server
      - -b
      - "0.0.0.0"
      - -p
      - "3000"
    ports:
      - "3002:3000"
    volumes:
      - ./backend:/rails:delegated    # ← mac 用にパフォーマンス向上
    environment:
      RAILS_ENV: development
      RAILS_LOG_TO_STDOUT: "true"

  frontend:
    build:
      context: ./frontend
    working_dir: /app
    command: npm run dev
    ports:
      - "3001:3000"
    volumes:
      - ./frontend:/app:cached             # ソースコード同期（mac 用：:cached）
      - frontend_node_modules:/app/node_modules  # 依存だけ永続化
    restart: unless-stopped

volumes:
  frontend_node_modules:                  # 永続化ボリューム定義
