version: '3.8'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    working_dir: /rails
    entrypoint:
      - bash
      - /rails/entrypoint.sh
    command:
      - bundle
      - exec
      - rails
      - server
      - -b
      - "0.0.0.0"
      - -p
      - "3000"
    ports:
      - "3002:3000"
    volumes:
      - type: bind
        source: ./backend
        target: /rails
        consistency: delegated    # mac でのパフォーマンス向上
    environment:
      RAILS_ENV: development
      RAILS_LOG_TO_STDOUT: "true"
    tty: true                    # Ctrl-C 等のシグナルを正しく受け取る
    stdin_open: true

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    working_dir: /app
    command: npm run dev
    ports:
      - "3001:3000"
    volumes:
      - type: bind
        source: ./frontend
        target: /app
        consistency: cached       # mac でのパフォーマンス向上
      - type: volume
        source: frontend_node_modules
        target: /app/node_modules
    restart: unless-stopped

volumes:
  frontend_node_modules:
